### ISSUE TITLE
sometimes auto-firing not working for blashphemy 

### ISSUE THREAD

**Issue by javers42** [pcrain/Gunfig#2] opened 2024-11-16 12:38 UTC
sometimes, auto-firing for semi-automatic weapons feature 
not working for blashphemy

**Comment by pcrain** [comment] 2024-11-17 00:28
@javers42 Can you provide more detail on what you mean exactly? :open_mouth: I just tested it and Blasphemy is in fact firing at its maximum fire rate when holding down fire while "Auto-fire Semi-Automatic Weapons" is active.

https://github.com/user-attachments/assets/f5ccfe7d-bf46-4ce6-862e-2c2bbca76b64

**Comment by pcrain** [comment] 2024-11-28 02:50
I'm unable to reproduce this without more information, so closing for now. Let me know if you have more information you can provide and I can look into it further. :slightly_smiling_face:

**Closed as not planned by pcrain** 2024-11-28 02:50 UTC
Labels: trying to reproduce
